rootProject.name = "train-ticket"
include(
    "modules:bff",
    "modules:booking:api-adapters",
    "modules:booking:api-model",
    "modules:booking:bootstrap",
    "modules:booking:domain",
    "modules:booking:persistence-adapters",
    "modules:booking:provider-adapters",
    "modules:booking:vsa-acl",
    "modules:exchange",
    "modules:shared-libs:business",
    "modules:shared-libs:clients",
    "modules:shared-libs:controller",
    "modules:shared-libs:tech:id",
    "modules:shared-libs:tech:logging",
    "modules:shared-libs:tech:controller",
    "modules:shared-libs:tech:jackson",
    "modules:shared-libs:tech:tests",
    "modules:shared-libs:tech:errors",
    "modules:shared-libs:tech:monitoring",
    "modules:shared-libs:tech:aws:propertysource"
)
